# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Season 2015"
email: "gdgbarcelona@gmail.com "
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://gdgbarcelona.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-57928606-1"
googleAnalyticsSiteUrl: "gdgbarcelona.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Barcelona"
organizerAlternateName: "Google Developer Group Barcelona"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdgbarcelona@gmail.com "
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgbarcelona.blogspot.com.es/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, Barcelona"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}

bottomNavigationLinks:
 - {link: "", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2015"
eventDate: "January, 2015"
typeoutTextValues: '"", "Season", "Barcelona", "Catalonia", "ESP"'
typeoutFallback: "Season"
heroButtons:
 - {link: "", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "600", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "9", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "6", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Campus Nord, Universitat Politècnica de Catalunya"
eventLocationLink: "http://www.upc.cat"
eventStreetAddress: "1 Carrer de Jordi Girona"
eventAddressLocality: "Barcelona"
eventAddressLocalityRegion: "Barcelona"
eventPostalCode: "08034"
eventAddressCountry: "Spain"
eventStartTime: "2015-01-16T8:30"
eventDoorTime: "09:00"
eventEndTime: "2015-01-16T19:00"
eventPlaceCoordinates: "41.389028,2.112551"
mapCenterCoordinates: "41.389028,2.112551"
mapMobileCenterCoordinates: "41.389028,2.112551"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Campus Nord"
venueFeatures: ["Universitat Politècnica de Catalunya"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "GDG Devfest Barcelona"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration is now open!!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "Free"
  priceCurrency: "Euros"
  ticketsNumber: "500"
  ribbon: "Free"
  buyButtonLink: "https://www.eventbrite.es/e/entradas-devfest-barcelona-2015-14961794129"
  buyButtonText: "Buy Now"
  ticketContentList: ["General Ticket"]
  validFrom: "2014-12-15T10:00"
  validThrough: "2015-01-16T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/gdgbarcelona", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGBarcelona", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "gdgbarcelona.blogspot.com.es", text: "GDG Barcelona"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdgbarcelona@gmail.com ", text: "gdgbarcelona@gmail.com "}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "41.389028,2.112551"
logisticsMapMobileCenterCoordinates: "41.389028,2.112551"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Barcelona"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.aena.es/csee/Satellite/Aeropuerto-Barcelona">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Barcelona. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Barcelona.'}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
- {title: "Remotte",image: "hackathon-1.png"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Jueces"

# Hackathon Prizes Block
prizesTitle: "Premios"
prizes:
- {title: "1nd Place Remotte ", image: "prize-1.png", info: "Remotte"}


# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "UPC"
hackathonLocationLink: "http://www.upc.cat/"
hackathonStreetAddress: "1 Carrer de Jordi Girona"
hackathonAddressLocality: "Barcelona"
hackathonAddressLocalityRegion: "Catalonia"
hackathonPostalCode: "08034"
hackathonAddressCountry: "Spain"
hackathonTimeTitle: "Hack "
hackathonStartTime: "2015-01-16T08:30"
hackathonDoorTime: "09:30"
hackathonEndTime: "2015-01-16T19:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "41.389028,2.112551"
hackathonMapCenterCoordinates: "41.389028,2.112551"
hackathonMapMobileCenterCoordinates: "41.389028,2.112551"





